// GENERATED By migration_gen.sh

package migration

import (
	"booking_server/internal/models"

	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

var initbookingschema20240725123737 = &gormigrate.Migration{
	ID: "20240725123737",
	Migrate: func(db *gorm.DB) error {
		return db.AutoMigrate(
			&models.Booking{},
		)
	},
	Rollback: func(db *gorm.DB) error {
		return db.Migrator().DropTable(&models.Booking{})
	},
}
