// GENERATED By migration_gen.sh

package migration

import (
	"booking_server/internal/models"

	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

var initpaymentschema20240725125350 = &gormigrate.Migration{
	ID: "20240725125350",
	Migrate: func(db *gorm.DB) error {
		return db.AutoMigrate(
			&models.Payment{},
		)
	},
	Rollback: func(db *gorm.DB) error {
		return db.Migrator().DropTable(&models.Payment{})
	},
}
