// GENERATED By migration_gen.sh

package migration

import (
	"booking_server/internal/models"

	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

var addexpireattobookings20240921175559 = &gormigrate.Migration{
	ID: "20240921175559",
	Migrate: func(db *gorm.DB) error {
		return db.AutoMigrate(
			&models.Booking{},
		)
	},
	Rollback: func(db *gorm.DB) error {
		return db.Migrator().DropColumn(&models.Booking{}, "expire_at")
	},
}
